version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lexqabot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11vns34sasgrg"
s3_prefix = "lexqabot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "personal"
